### ISSUE TITLE
Daisy pipeline 1 conversion issues

### ISSUE THREAD

**Issue by Iamsrinath5** [daisy/pipeline1#3]
I am trying to run Braille to text script and facing the issue with JobFailedException
org.daisy.braille.embosser.EmbosserCatalog is not an ImageIO SPI class

**Comment by rdeltour** [comment]
> Ah it's because pipeline1 has no issues.

right, I just noticed this too ( I was started to bang my head). I enabled the issue tracker and transferred the issue.

**Comment by Iamsrinath5** [comment]
Please help me with using below commands:
I face following issue while running dtbook_to_brailleDtbook script
 Error at xsl:value-of on line 27 of DP1/transformers/ch_sbs_dtbook2translatedbrailledtbook/dtbook2translatedBrailleDtbook.xsl:
ERR :   XPST0003: XPath syntax error at char 35 on line 27 in {...:translate($liblouis_table,...}:
ERR :     Cannot find a matching 2-argument function named {java:org.liblouis.Louis}translate()

Here is the command i tried to run
pipeline.bat scripts\create_distribute\dtbook\DTBookToTranslatedBrailleDTBook.taskScript "--input=C:\input\greatpainters\greatpainters.xml" "--output=C:\input\braille_out"

Please refer to the complete log file 
[greatpainters.log](https://github.com/daisy/pipeline1/files/3992791/greatpainters.log)

**Comment by Iamsrinath5** [comment]
Command i tried to run:

pipeline.bat scripts\create_distribute\text\BraillePefToText.taskScript "--input=C:\input\pef\pef-output-dir\greatpainters.pef" "--output=C:\input\br_text" "--table=org_daisy.EmbosserTableProvider.TableType.UNICODE_BRAILLE"

Problem i get:

org.daisy.braille.embosser.EmbosserCatalog is not an ImageIO SPI class
org.daisy.pipeline.exception.JobFailedException: Error running script: org.daisy.braille.embosser.EmbosserCatalog is not an ImageIO SPI class.
        at org.daisy.pipeline.core.script.Runner.execute(Runner.java:124)
        at org.daisy.pipeline.core.PipelineCore.execute(PipelineCore.java:280)
        at org.daisy.pipeline.ui.CommandLineUI.main(CommandLineUI.java:213)
java.lang.IllegalArgumentException: org.daisy.braille.embosser.EmbosserCatalog is not an ImageIO SPI class
        at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:722)
        at java.desktop/javax.imageio.spi.ServiceRegistry.lookupProviders(ServiceRegistry.java:207)
        at org.daisy.braille.embosser.EmbosserCatalog.newInstance(EmbosserCatalog.java:45)
        at org_pef_text.pef2text.PEF2Text.execute(PEF2Text.java:66)
        at org.daisy.pipeline.core.transformer.Transformer.executeWrapper(Transformer.java:174)
        at org.daisy.pipeline.core.transformer.TransformerHandler.run(TransformerHandler.java:124)
        at org.daisy.pipeline.core.script.Runner.execute(Runner.java:98)
        at org.daisy.pipeline.core.PipelineCore.execute(PipelineCore.java:280)
        at org.daisy.pipeline.ui.CommandLineUI.main(CommandLineUI.java:213)
